<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NJsonSchema" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Sipos.Resume.Core" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3" />
    <Using Include="Shouldly" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="jsonresume-schema.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
